# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-29 02:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='areainfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('arealevel', models.IntegerField()),
                ('parea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Buyers.areainfo')),
            ],
            options={
                'db_table': 'areainfo',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=30)),
                ('gDate', models.DateField(auto_now=True)),
                ('gAbout', models.CharField(max_length=100)),
                ('gStore', models.IntegerField()),
                ('gcontent', ckeditor.fields.RichTextField(verbose_name='\u5185\u5bb9')),
                ('gPrice', models.FloatField()),
                ('gSales', models.IntegerField(default=0)),
                ('gimg', models.CharField(max_length=300)),
                ('gTtype', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnameing', models.CharField(max_length=50)),
                ('gimage', models.CharField(max_length=300)),
                ('gItype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyers.Goods')),
            ],
            options={
                'db_table': 'GoodsImg',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goffers', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Label',
            },
        ),
        migrations.CreateModel(
            name='Ucart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uc_state', models.NullBooleanField(default=None)),
                ('Ucontent', models.CharField(max_length=300)),
                ('Uc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyers.Goods')),
            ],
            options={
                'db_table': 'Ucart',
            },
        ),
        migrations.CreateModel(
            name='Upost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=100)),
                ('Popen', models.BooleanField(default=True)),
                ('Plabel', models.CharField(max_length=30)),
                ('Pcontent', ckeditor.fields.RichTextField(verbose_name='\u5185\u5bb9')),
            ],
            options={
                'db_table': 'Upost',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upet', models.CharField(max_length=20)),
                ('Uname', models.CharField(max_length=20)),
                ('Upswd', models.CharField(max_length=30)),
                ('Uphone', models.CharField(max_length=20)),
                ('Uemail', models.CharField(max_length=30)),
                ('Uadd', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='upost',
            name='Ptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyers.User'),
        ),
        migrations.AddField(
            model_name='ucart',
            name='Utype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyers.User'),
        ),
        migrations.AddField(
            model_name='goods',
            name='gLtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyers.Label'),
        ),
        migrations.AddField(
            model_name='goods',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Back.Seller_User'),
        ),
    ]
