# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-29 02:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Buyers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userbbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uimg', models.ImageField(null=True, upload_to='img')),
                ('Uname', models.CharField(max_length=20)),
                ('Uemail', models.CharField(max_length=20)),
                ('Upswd', models.CharField(max_length=30)),
                ('Uabout', models.CharField(max_length=200, null=True)),
                ('Usex', models.NullBooleanField(default=None)),
            ],
            options={
                'db_table': 'Userbbs',
            },
        ),
        migrations.CreateModel(
            name='Usercomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ctxt', models.CharField(max_length=100)),
                ('Cdate', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Usercomment',
            },
        ),
        migrations.CreateModel(
            name='Useressay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Etitle', models.CharField(max_length=100)),
                ('Etext', ckeditor.fields.RichTextField(verbose_name='\u5185\u5bb9')),
                ('Estate', models.BooleanField(default=True)),
                ('Edate', models.DateField(auto_now=True)),
                ('Eauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Userbbs')),
                ('Eproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyers.Goods')),
            ],
            options={
                'db_table': 'Useressay',
            },
        ),
        migrations.CreateModel(
            name='Usersort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ssort', models.CharField(max_length=50)),
                ('Stxt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Userstores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Smy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Userbbs')),
                ('Spost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Useressay')),
            ],
        ),
        migrations.AddField(
            model_name='useressay',
            name='Esort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Usersort'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='Cessay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Useressay'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='Cname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Userbbs'),
        ),
    ]
